language: php
php:
  - '7.4'
  - '8.0'
  - '8.1'
install:
  - 'make install'
before_script:
  - 'echo "xdebug.mode = coverage" >>~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini'
script:
  - 'make test lint'
